// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bVUzgGEMiTlW7VF912JZK8o9LYiddE4',
    appId: '1:671256677241:web:00418c32a4dbf88c087da8',
    messagingSenderId: '671256677241',
    projectId: 'ra7alh-c2ac6',
    authDomain: 'ra7alh-c2ac6.firebaseapp.com',
    storageBucket: 'ra7alh-c2ac6.appspot.com',
    measurementId: 'G-VJK56GCDLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUFtnv-e_91JHsbnveRa0UAEydN-IzHN4',
    appId: '1:671256677241:android:740d6b49e9652114087da8',
    messagingSenderId: '671256677241',
    projectId: 'ra7alh-c2ac6',
    storageBucket: 'ra7alh-c2ac6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVh4NAPB8eHQu5vGS5GTurnrvZhPkpAD4',
    appId: '1:671256677241:ios:e68a03db413f22ed087da8',
    messagingSenderId: '671256677241',
    projectId: 'ra7alh-c2ac6',
    storageBucket: 'ra7alh-c2ac6.appspot.com',
    iosBundleId: 'com.eslamfares.ra7alh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVh4NAPB8eHQu5vGS5GTurnrvZhPkpAD4',
    appId: '1:671256677241:ios:7f1b7d79664b021a087da8',
    messagingSenderId: '671256677241',
    projectId: 'ra7alh-c2ac6',
    storageBucket: 'ra7alh-c2ac6.appspot.com',
    iosBundleId: 'com.eslamfares.ra7alh.RunnerTests',
  );
}
